# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"geturl": "00_external.ipynb",
         "sync": "00_external.ipynb",
         "USERAGENT": "00_external.ipynb",
         "DESC": "00_external.ipynb",
         "Ladsweb": "01_download.ipynb",
         "run_parallel": "01_download.ipynb",
         "geoget_ladsweb": "02_cli.ipynb"}

modules = ["external.py",
           "download.py",
           "cli.py"]

doc_url = "https://mnpinto.github.io/geoget/"

git_url = "https://github.com/mnpinto/geoget/tree/master/"

def custom_doc_links(name): return None
